// very silly script to sort map by keys.
// not included in build system
const obj = {
    "707AF1":                       "B703",
    "747AF1":                       "B742",
    "A6M Zero":                     "ZERO",
    "A10 Warthog":                  "A10",
    "A330 MRTT":                    "A332",
    "Airbus A220":                  "BCS1",
    "Airbus A320":                  "A320",
    "Airbus A330":                  "A333",
    "Airbus A340":                  "A343",
    "Airbus A350":                  "A359",
    "Airbus A380":                  "A388",
    "Airbus Beluga":                "A3ST",
    "An22":                         "AN22",
    "An 225":                       "A225",
    "ATR72":                        "AT76",
    "ATR72F":                       "AT76",
    "Avro Vulcan":                  "VULC",
    "B1 Lancer":                    "B1",
    "B2 Spirit Bomber":             "B2",
    "B29 SuperFortress":            "B29",
    "BaggageTruck":                 "GRND",
    "BaggageTruckSmall":            "GRND",
    "Balloon":                      "BALL",
    "Bell 412 Rescue":              "B412",
    "Bell 412":                     "B412",
    "Blimp":                        "SHIP",
    "Boeing 707":                   "B703",
    "Boeing 727 Cargo":             "B722",
    "Boeing 727":                   "B722",
    "Boeing 737 Cargo":             "B738",
    "Boeing 737":                   "B738",
    "Boeing 747 Cargo":             "B744",
    "Boeing 747":                   "B744",
    "Boeing 757 Cargo":             "B752",
    "Boeing 757":                   "B752",
    "Boeing 767 Cargo":             "B763",
    "Boeing 767":                   "B763",
    "Boeing 777 Cargo":             "B77L",
    "Boeing 777":                   "B77W",
    "Boeing 787":                   "B789",
    "Bombardier CRJ700":            "CRJ7",
    "Bombardier Learjet 45":        "LJ45",
    "Bombardier Q400":              "DH8D",
    "Bus":                          "GRND",
    "C17":                          "C17",
    "C40":                          "B737",
    "C130 Hercules":                "C130",
    "C-32":                         "B752",
    "Caproni Stipa":                "ZZZZ",
    "CaravanBlimp":                 "SHIP",
    "CateringTruck":                "GRND",
    "Cessna 172 Amphibian":         "C172",
    "Cessna 172 Student":           "C172",
    "Cessna 172":                   "C172",
    "Cessna 182 Amphibian":         "C182",
    "Cessna 182":                   "C182",
    "Cessna 402":                   "C402",
    "Cessna Caravan Amphibian":     "C208",
    "Cessna Caravan Cargo":         "C208",
    "Cessna Caravan":               "C208",
    "Chinook":                      "H47",
    "Cirrus Vision":                "SF50",
    "Concorde":                     "CONC",
    "Derek Plane":                  "ULAC",
    "DHC-6 Twin Otter Amphibian":   "DHC6",
    "DHC-6 Twin Otter":             "DHC6",
    "Douglas MD11 Cargo":           "MD11",
    "Douglas MD11":                 "MD11",
    "Douglas MD90":                 "MD90",
    "DreamLifter":                  "BLCF",
    "E190":                         "E190",
    "E-3 Sentry":                   "E3TF",
    "EC-18B":                       "C135",
    "English Electric Lightning":   "LTNG",
    "Eurofighter Typhoon":          "EUFI",
    "Extra 300s":                   "E300",
    "F4 Phantom":                   "F4",
    "F4U Corsair":                  "CORS",
    "F14":                          "F14",
    "F15":                          "F15",
    "F16":                          "F16",
    "F22":                          "F22",
    "F35":                          "F35",
    "F/A-18 Super Hornet":          "F18S",
    "FireTruck":                    "GRND",
    "Fokker Dr1":                   "DR1",
    "FollowMeTruck":                "GRND",
    "FuelTruck":                    "GRND",
    "FuelTruckSmall":               "GRND",
    "Gripen":                       "SB39",
    "H135":                         "EC35",
    "Harrier":                      "HAR",
    "Hawk T1":                      "HAWK",
    "Hurricane":                    "HURI",
    "KC130J":                       "C30J",
    "KC767":                        "B762",
    "KC-1":                         "L101",
    "KC-707":                       "B703",
    "KingAir 260":                  "BE20",
    "Lockheed Tristar":             "L101",
    "Mig-15":                       "MG15",
    "Might Walrus":                 "ZZZZ",
    "P8":                           "P8",
    "P38 Lightning":                "P38",
    "P51 Mustang":                  "P51",
    "Paratrike":                    "PARA",
    "Piper Cub Amphibian":          "J3",
    "Piper Cub":                    "J3",
    "Piper PA28181":                "P28A",
    "PushBackBig":                  "GRND",
    "PushBackGreen":                "GRND",
    "PushBackSmall":                "GRND",
    "Rescue Boat":                  "ZZZZ",
    "Sikorsky S92 Coast Guard":     "S92",
    "Sikorsky S92":                 "S92",
    "Sled":                         "SLEI",
    "SR71 BlackBird":               "SR71",
    "StairTruck737":                "GRND",
    "StairTruck":                   "GRND",
    "SU27":                         "SU27",
    "SU57":                         "SU57",
    "UFO":                          "ZZZZ",
    "UH-60 Coast Guard":            "H60",
    "UH-60":                        "H60",
    "Wright Brothers Plane":        "WF"
}

const map = Object.entries(obj);

// cursed
map.sort(([key1, val1], [key2, val2]) => [val1, val2].sort().indexOf(val1)-1);

console.log("{");

map.forEach(([key, val]) => {
    const sp_count = 32 - key.length - 3;
    const sps = " ".repeat(sp_count);
    console.log(`    "${key}":${sps}"${val}",`);
});
console.log("}");